openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'

tags:
  - name: login
paths:
  /test:
    get:
      summary: test.
      tags:
        - login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestOk'
components:
  schemas:
    TestOk:
      type: string
